# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/playwright:next

WORKDIR /app

COPY ["./package.json", "./package-lock.json", "./"]
RUN npm install
RUN npx playwright install --with-deps chromium
