name: Publish to NPM
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
permissions: {}
jobs:
  ci:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for codeql-action
    uses: ./.github/workflows/ci.yml

  changelog:
    permissions:
      contents: read # for actions/checkout
    uses: ./.github/workflows/changelog.yml

  npm-publish:
    environment:
      name: npm-publish
      url: https://www.npmjs.com/package/graphql-voyager/v/${{github.ref_name}}
    needs:
      - ci
      - changelog
    permissions:
      contents: read # for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: npm
          node-version-file: 'package.json'
          # 'registry-url' is required for 'npm publish'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: npmDist
          path: npmDist

      - name: Publish package on NPM
        run: npm publish ./npmDist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
